/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ImpactDnaRouteImport } from './routes/impact-dna'
import { Route as MaintenanceTasksRouteImport } from './routes/maintenance-tasks'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SpecialTrainsRouteImport } from './routes/special-trains'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactDnaRoute = ImpactDnaRouteImport.update({
  id: '/impact-dna',
  path: '/impact-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceTasksRoute = MaintenanceTasksRouteImport.update({
  id: '/maintenance-tasks',
  path: '/maintenance-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialTrainsRoute = SpecialTrainsRouteImport.update({
  id: '/special-trains',
  path: '/special-trains',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/conflicts': typeof ConflictsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/impact-dna': typeof ImpactDnaRoute
  '/maintenance-tasks': typeof MaintenanceTasksRoute
  '/optimizer': typeof OptimizerRoute
  '/planner': typeof PlannerRoute
  '/requests': typeof RequestsRoute
  '/simulation': typeof SimulationRoute
  '/special-trains': typeof SpecialTrainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/conflicts': typeof ConflictsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/impact-dna': typeof ImpactDnaRoute
  '/maintenance-tasks': typeof MaintenanceTasksRoute
  '/optimizer': typeof OptimizerRoute
  '/planner': typeof PlannerRoute
  '/requests': typeof RequestsRoute
  '/simulation': typeof SimulationRoute
  '/special-trains': typeof SpecialTrainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/conflicts': typeof ConflictsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/impact-dna': typeof ImpactDnaRoute
  '/maintenance-tasks': typeof MaintenanceTasksRoute
  '/optimizer': typeof OptimizerRoute
  '/planner': typeof PlannerRoute
  '/requests': typeof RequestsRoute
  '/simulation': typeof SimulationRoute
  '/special-trains': typeof SpecialTrainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/conflicts'
    | '/dashboard'
    | '/emergency'
    | '/impact-dna'
    | '/maintenance-tasks'
    | '/optimizer'
    | '/planner'
    | '/requests'
    | '/simulation'
    | '/special-trains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/conflicts'
    | '/dashboard'
    | '/emergency'
    | '/impact-dna'
    | '/maintenance-tasks'
    | '/optimizer'
    | '/planner'
    | '/requests'
    | '/simulation'
    | '/special-trains'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/conflicts'
    | '/dashboard'
    | '/emergency'
    | '/impact-dna'
    | '/maintenance-tasks'
    | '/optimizer'
    | '/planner'
    | '/requests'
    | '/simulation'
    | '/special-trains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConflictsRoute: typeof ConflictsRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyRoute: typeof EmergencyRoute
  ImpactDnaRoute: typeof ImpactDnaRoute
  MaintenanceTasksRoute: typeof MaintenanceTasksRoute
  OptimizerRoute: typeof OptimizerRoute
  PlannerRoute: typeof PlannerRoute
  RequestsRoute: typeof RequestsRoute
  SimulationRoute: typeof SimulationRoute
  SpecialTrainsRoute: typeof SpecialTrainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-dna': {
      id: '/impact-dna'
      path: '/impact-dna'
      fullPath: '/impact-dna'
      preLoaderRoute: typeof ImpactDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-tasks': {
      id: '/maintenance-tasks'
      path: '/maintenance-tasks'
      fullPath: '/maintenance-tasks'
      preLoaderRoute: typeof MaintenanceTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-trains': {
      id: '/special-trains'
      path: '/special-trains'
      fullPath: '/special-trains'
      preLoaderRoute: typeof SpecialTrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConflictsRoute: ConflictsRoute,
  DashboardRoute: DashboardRoute,
  EmergencyRoute: EmergencyRoute,
  ImpactDnaRoute: ImpactDnaRoute,
  MaintenanceTasksRoute: MaintenanceTasksRoute,
  OptimizerRoute: OptimizerRoute,
  PlannerRoute: PlannerRoute,
  RequestsRoute: RequestsRoute,
  SimulationRoute: SimulationRoute,
  SpecialTrainsRoute: SpecialTrainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
